In [8]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20],[30, 40]])

print("a + b:\n", a + b)
print("a * 2:\n", a * 2)
print("a的平均值:", a.float().mean())

a + b:
 tensor([[11, 22],
        [33, 44]])
a * 2:
 tensor([[2, 4],
        [6, 8]])
a的平均值: tensor(2.5000)


In [6]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 你的代码：取出7
result = x[1, 2]  # 把?换成数字，索引从0开始
print(result)

tensor(7)


In [5]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("原始矩阵:\n", x)
print(f"\n第1行: {x[0]}")
print(f"第2列: {x[:, 1]}")
print(f"子矩阵[0:2, 1:3]: \n{x[0:2, 1:3]}")

原始矩阵:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

第1行: tensor([1, 2, 3, 4])
第2列: tensor([ 2,  6, 10])
子矩阵[0:2, 1:3]: 
tensor([[2, 3],
        [6, 7]])


In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"数据：\n{x}")
print(f"形状 (shape) : {x.shape}")
print(f"维度数 (ndim) : {x.ndim}")
print(f"数据类型 (dtype) : {x.dtype}")
print(f"元素个数 (numel) : {x.numel()}")

数据：
tensor([[1, 2, 3],
        [4, 5, 6]])
形状 (shape) : torch.Size([2, 3])
维度数 (ndim) : 2
数据类型 (dtype) : torch.int64
元素个数 (numel) : 6


In [3]:
# 方法1：从数据创建
t1 = torch.tensor([[1, 2], [3, 4]])
print("方法1 - 从数据:", t1)

# 方法2：全0
t2 = torch.zeros(2, 3)
print("方法2 - zeros:", t2)

# 方法3：全1
t3 = torch.ones(3, 2)
print("方法3 - ones:", t3)

# 方法4：随机（0-1均匀分布）
t4 = torch.rand(2, 2)
print("方法4 - rand:", t4)

# 方法5：随机（标准正态分布）
t5 = torch.randn(2, 3)
print("方法5 - randn:", t5)

方法1 - 从数据: tensor([[1, 2],
        [3, 4]])
方法2 - zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
方法3 - ones: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
方法4 - rand: tensor([[0.7135, 0.9524],
        [0.1862, 0.2772]])
方法5 - randn: tensor([[ 1.1925,  1.6715, -1.1703],
        [-0.4813, -1.7188, -0.0318]])


In [ ]:
import torch
print(f"PyTorch版本: {torch.__version__}")
print(f"CUDA可用: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")